
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 02 18:16:53 CET 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int GREATER_OR_EQUAL = 38;
  public static final int CONST = 6;
  public static final int EQUALS = 8;
  public static final int STRCONST = 12;
  public static final int NOT_EQUAL = 36;
  public static final int GREATER = 37;
  public static final int LPAREN = 19;
  public static final int SEMI_COMMA = 7;
  public static final int LESS = 39;
  public static final int MINUS = 32;
  public static final int RPAREN = 20;
  public static final int AND = 31;
  public static final int LESS_OR_EQUAL = 40;
  public static final int OR = 30;
  public static final int COMMA = 13;
  public static final int CLASS = 16;
  public static final int INC = 21;
  public static final int DIV = 43;
  public static final int PLUS = 41;
  public static final int IF = 23;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 35;
  public static final int RBRACKET = 15;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 44;
  public static final int NUMBER = 9;
  public static final int BREAK = 25;
  public static final int IDENT = 3;
  public static final int VOID = 18;
  public static final int TIMES = 42;
  public static final int LBRACE = 4;
  public static final int ELSE = 28;
  public static final int READ = 27;
  public static final int CHARCONST = 10;
  public static final int WHILE = 24;
  public static final int RBRACE = 5;
  public static final int BOOLCONST = 11;
  public static final int EXTENDS = 17;
  public static final int DEC = 22;
  public static final int PRINT = 29;
}

